version: "3.9"

services:
  app:
    image: node:latest
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
      - /config:/mnt/user/appdata/getting-started
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: mysecret
      MYSQL_DB: todos

  mysql:
    image: mysql:latest
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: mysecret
      MYSQL_DATABASE: todos

volumes:
  todo-mysql-data:
